apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dependencies-valume-claim
  namespace: dependencies
  labels:
    type: longhorn
    app: dependencies-graph
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi