apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: dependencies-issuer-prod
spec:
  acme:
    email: xavier.clemence@gmail.com
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: dependencies-tls-key
    solvers:
    - http01:
        ingress:
          class: nginx
