version: '3'

services:
  db:
    image: neo4j:4.0.4
    ports: 
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - ../data/neo4j:/data
