apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-keycloak-config
  namespace: dep-graph
  labels:
    app: postgres
data:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: password

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dep-graph
  name: postgres-keycloak
spec:
  serviceName: postgres-keycloak
  replicas: 1
  selector:
    matchLabels:
      app: postgres-keycloak
  template:
    metadata:
      labels:
        app: postgres-keycloak
    spec:
      serviceAccountName: useroot
      containers:
      - name: postgres
        image: postgres:13-alpine
        envFrom:
        - configMapRef:
            name: postgres-keycloak-config
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-keycloak-db
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-keycloak-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi