apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: dep-graph
  labels:
    app: neo4j
data:
  NEO4J_AUTH: none
  NEO4JLABS_PLUGINS: "[\"apoc\"]"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: dep-graph
  labels:
    app: neo4j
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:4.2.7
        envFrom:
        - configMapRef:
            name: neo4j-config
        ports:
        - containerPort: 7473
          protocol: TCP
        - containerPort: 7474
          protocol: TCP
        - containerPort: 7687
          protocol: TCP
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: dependencies-storage
      - name: neo4j-logs
        emptyDir: {}

