version: '3'

services:
  graph-service:
    image: dependencies-graph-api:test
    build:
      context: "${PROJECTS_DIR}/dependencies-graph-services/src"
      dockerfile: Dependencies.Graph.Api/Dockerfile
    ports: 
      - 5000:80
    environment:
      - GraphConfig__Uri=bolt://neo4j_db_1
      - ASPNETCORE_URLS=http://*:80

networks:
  default:
    name: graph_network
    external: true