apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dependencies-storage
  namespace: dep-graph
  labels:
    app: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
