---

- name: ensure manifest dir exists
  file:
    path: "{{manifest_base_dir}}/graph/rest"
    state: directory

- name: create manifest template config map
  template:
    src: rest-config-map.yaml
    dest: "{{manifest_base_dir}}/graph/rest/rest-config-map.yaml"

- name: Apply config map
  community.kubernetes.k8s:
    state: present
    kubeconfig: "{{ kube_config_file }}"
    src: "{{manifest_base_dir}}/graph/rest/rest-config-map.yaml"
    namespace: graph

- name: create manifest template graphql
  template:
    src: rest.yaml
    dest: "{{manifest_base_dir}}/graph/rest/rest.yaml"

- name: Apply rest
  community.kubernetes.k8s:
    state: present
    kubeconfig: "{{ kube_config_file }}"
    src: "{{manifest_base_dir}}/graph/rest/rest.yaml"
    namespace: graph

- name: create manifest template ingress
  template:
    src: rest-ingress.yaml
    dest: "{{manifest_base_dir}}/graph/rest/rest-ingress.yaml"

- name: Apply rest ingress
  community.kubernetes.k8s:
    state: present
    kubeconfig: "{{ kube_config_file }}"
    src: "{{manifest_base_dir}}/graph/rest/rest-ingress.yaml"
    namespace: graph

