apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak
  labels:
    app: postgres-keycloak
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgres-keycloak
