apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rest-api
  namespace: dep-graph
  labels:
    app: dependencies-graph-api
spec:
  path: /
  to:
    kind: Service
    name: rest-api-service
  port:
    targetPort: 8000