apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-config
  namespace: dep-graph
  labels:
    app: dependencies-graph-api
data:
  GraphConfig__Uri: bolt://neo4j-service
  ASPNETCORE_URLS: http://*:8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rest-api
  namespace: dep-graph
  labels:
    app:  dependencies-graph-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  dependencies-graph-api
  template:
    metadata:
      labels:
        app:  dependencies-graph-api
    spec:
      imagePullSecrets:
      - name: github
      containers:
      - name:  dependencies-graph-api
        image: ghcr.io/xclemence/dependencies-graph-api:2.0.0
        envFrom:
        - configMapRef:
            name: rest-config
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: api-logs
          mountPath: /api/logs
      volumes:
      - name: api-logs
        emptyDir: {}

