apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
  namespace: dep-graph
  labels:
    app: dependencies-graph-api
spec:
  selector:
    app: dependencies-graph-api
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000

