apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  namespace: dependencies
spec:
  selector:
    app: neo4j
  ports:
    - protocol: TCP
      name: http
      port: 7473
      targetPort: 7473
    - protocol: TCP
      name: https
      port: 7474
      targetPort: 7474
    - protocol: TCP
      name: bolt
      port: 7687
      targetPort: 7687


