version: '3'

services:
  dependencies-graph-viewer :
    image: dependencies-graph-viewer:test
    build:
      context: "${PROJECTS_DIR}/dependencies-graph-viewer"
      dockerfile: Dockerfile
    ports: 
      - 4100:80
    environment: 
      - DEPENDENCIES_GRAPHQL_URI=http://localhost:4001/graphql
      - SECURITY_ENABLED=false
      - SECURITY_SERVER=http://localhost:9080/auth
      - SECURITY_REALM=dependencies
      - SECURITY_CLIENT_ID=graph

networks:
  default:
    name: graph_network
    external: true